[project]
name = "cargo"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.cargo]
path = "contracts/cargo.clar"
depends_on = []
